bake_cake/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bakery.urls')),
]

bakery/urls.py
from . import views
from django.urls import path

app_name = "bakery"

urlpatterns = [
    path('', views.view_index, name='main_page'),
    path('lk/', views.view_lk, name='lk_page'),
    path('order_cake/', views.order_cake, name='order_cake'),
    path('cakes/', views.view_cakes_from_catalogue, name='view_cakes_from_catalogue'),
    path('order_cake_from_catalogue/', views.order_cake_from_catalogue, name='order_cake_from_catalogue'),
    path('cancel/', views.cancel, name='cancel'),
    path('success/', views.success, name='success'),

]

bakery/models.py
from datetime import datetime, timedelta
from django.utils import timezone
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator


class User(models.Model):
    name = models.CharField(
        'Имя',
        max_length=30,
    )
    phone_number = PhoneNumberField(
        'Номер телефона',
        region='RU'
    )
    email = models.EmailField(
        'Почта',
        max_length=60,
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.name


class CakeLevel(models.Model):
    level = models.PositiveSmallIntegerField(
        verbose_name='Кол-во уровней',
        unique=True,
        validators=[MinValueValidator(1)]
    )
    price = models.IntegerField(
        verbose_name='Стоимость'
    )

    class Meta:
        verbose_name = 'Уровень торта'
        verbose_name_plural = 'Уровни торта'

    def __str__(self):
        return str(self.level)


class CakeShape(models.Model):
    shape = models.CharField(
        max_length=50,
        verbose_name='Форма',
        unique=True
    )
    price = models.IntegerField(
        verbose_name='Стоимость'
    )

    class Meta:
        verbose_name = 'Форма торта'
        verbose_name_plural = 'Формы тортов'

    def __str__(self):
        return self.shape


class CakeTopping(models.Model):
    topping = models.CharField(
        max_length=50,
        verbose_name='Топпинг',
        unique=True
    )
    price = models.IntegerField(
        verbose_name='Стоимость'
    )

    class Meta:
        verbose_name = 'Топпинг торта'
        verbose_name_plural = 'Топпинги тортов'

    def __str__(self):
        return self.topping


class CakeBerry(models.Model):
    cake_berry = models.CharField(
        max_length=50,
        verbose_name='Ягоды',
    )
    price = models.IntegerField(
        verbose_name='Стоимость'
    )

    class Meta:
        verbose_name = 'Ягода'
        verbose_name_plural = 'Ягоды'

    def __str__(self):
        return self.cake_berry


class CakeDecor(models.Model):
    cake_decor = models.CharField(
        max_length=50,
        verbose_name='Декор'
    )
    price = models.IntegerField(
        verbose_name='Стоимость',
    )

    class Meta:
        verbose_name = 'Декор'
        verbose_name_plural = 'Декор'

    def __str__(self):
        return self.cake_decor


class Cake(models.Model):
    cake_name = models.CharField(
        'Название торта',
        max_length=30,
        default='Кастомный торт'
    )
    level = models.ForeignKey(
        CakeLevel,
        verbose_name='Кол-во уровней торта',
        on_delete=models.CASCADE,
        related_name='levels'
    )
    shape = models.ForeignKey(
        CakeShape,
        verbose_name='Форма торта',
        on_delete=models.CASCADE,
        related_name='shapes'
    )
    topping = models.ForeignKey(
        CakeTopping,
        verbose_name='Топпинг торта',
        on_delete=models.CASCADE,
        related_name='toppings',
    )
    berry = models.ForeignKey(
        CakeBerry,
        verbose_name='Ягоды',
        on_delete=models.CASCADE,
        related_name='berries',
        blank=True,
        null=True
    )
    decor = models.ForeignKey(
        CakeDecor,
        verbose_name='Декор',
        on_delete=models.CASCADE,
        related_name='decors',
        blank=True,
        null=True
    )
    image = models.CharField(
        'Путь к изображению торта',
        max_length=50,
        blank=True,
    )

    class Meta:
        verbose_name = 'Торт'
        verbose_name_plural = 'Торты'

    def __str__(self):
        return self.cake_name

    def total_price(self):
        total = self.level.price + self.shape.price + self.topping.price
        if self.berry:
            total += self.berry.price
        if self.decor:
            total += self.decor.price
        return total


class AdvetisementUrl(models.Model):
    title = models.CharField(
        'Название',
        max_length=50,
    )
    link = models.CharField(
        'Ссылка',
        max_length=20,
    )

    class Meta:
        verbose_name = 'Рекламная ссылка'
        verbose_name_plural = 'Рекламные ссылки'

    def __str__(self) -> str:
        return self.title
    

class AdvetisementUrlCount(models.Model):
    link = models.ForeignKey(
        AdvetisementUrl,
        on_delete=models.CASCADE,
        related_name='url',
        verbose_name='Ссылка',
    )
    date = models.DateField(
        'Дата',
              
    )
    total_clicks = models.IntegerField(
        'Количество',
    )

    class Meta:
        verbose_name = 'Количество просмотров'
        verbose_name_plural = 'Количество просмотров'


class Order(models.Model):
    STATUS_CHOICES = [
        ('OPEN', 'Необработанный'),
        ('PROGRESSING', 'Готовится'),
        ('Transit', 'В пути'),
        ('CLOSED', 'Закрыт')
    ]
    status = models.CharField(
        'Статус заказа',
        db_index=True,
        max_length=20,
        choices=STATUS_CHOICES,
        default='OPEN'
    )
    customer = models.ForeignKey(
        User,
        verbose_name='Клиент',
        related_name='orders',
        on_delete=models.CASCADE
    )
    cake = models.ForeignKey(
        Cake,
        verbose_name='Заказанный торт',
        related_name='orders',
        on_delete=models.PROTECT,
    )
    price = models.IntegerField(
        verbose_name='Стоимость',
    )
    registrated_at = models.DateTimeField(
        verbose_name='Дата регистрации заказа',
        auto_now_add=True,
        db_index=True,
    )
    delivery_address = models.CharField(
        'Адрес доставки',
        max_length=200,
        default='Москва, метро Китай-Город'
    )
    delivery_date = models.DateField(
        'Дата доставки',
        db_index=True
    )
    delivery_time = models.TimeField(
        'Время доставки',
        db_index=True
    )
    delivery_comments = models.TextField(
        verbose_name='Комментарий для курьера',
        blank=True
    )
    cake_text = models.CharField(
        max_length=50,
        blank=True,
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'{self.cake} {self.customer.name}'

    def total_order_price(self):
        total_order_price = self.cake.total_price()

        if self.cake_text:
            total_order_price += 500

        if self.delivery_date <= timezone.now().date() + timedelta(days=1):
            total_order_price *= 1.20

        return total_order_price

bakery/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404

from bakery.models import Cake, CakeLevel, CakeShape, CakeTopping, CakeBerry, CakeDecor
from bakery.services import create_order


@transaction.atomic
def order_cake(request):
    cake_name = 'Кастомный торт'

    level_id = int(request.POST.get('LEVELS'))
    shape_id = int(request.POST.get('FORM'))
    topping_id = int(request.POST.get('TOPPING', 0))
    berry_id = int(request.POST.get('BERRIES', 0))
    decor_id = int(request.POST.get('DECOR', 0))

    level = get_object_or_404(CakeLevel, level=level_id)
    shape = get_object_or_404(CakeShape, id=shape_id)
    topping = get_object_or_404(CakeTopping, id=topping_id) if topping_id else None
    berry = get_object_or_404(CakeBerry, id=berry_id) if berry_id else None
    decor = get_object_or_404(CakeDecor, id=decor_id) if decor_id else None

    cake_data = {
        'level': level,
        'shape': shape,
        'topping': topping,
        'berry': berry,
        'decor': decor,
    }

    return create_order(request, cake_name, cake_data)


@transaction.atomic
def order_cake_from_catalogue(request):
    cake_name = request.POST.get('LEVELS')

    return create_order(request, cake_name)


def view_index(request):
    levels = CakeLevel.objects.all()
    shapes = CakeShape.objects.all()
    toppings = CakeTopping.objects.all()
    berries = CakeBerry.objects.all()
    decors = CakeDecor.objects.all()

    return render(request, template_name='index.html',
                  context={
                      'levels': levels,
                      'shapes': shapes,
                      'toppings': toppings,
                      'berries': berries,
                      'decors': decors
                  })


def view_lk(request):
    return render(request, template_name='lk.html', context={})


def view_cakes_from_catalogue(request):
    cakes = Cake.objects.exclude(cake_name='Кастомный торт')
    return render(request, template_name='cakes.html', context={'cakes': cakes})


def success(request):
    return render(request, template_name='success.html')


def cancel(request):
    return render(request, template_name='cancel.html')

bakery/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/Style.css' %}">
	<!-- Для разработки: -->
	<script src="https://unpkg.com/vue@3"></script>
	<!-- Для продакшина: -->
	<!-- <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script> -->
	<script src="https://unpkg.com/vee-validate"></script>
	<title>Тортики</title>
</head>
<body>
<header class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-4">
	<nav class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{% url 'bakery:main_page' %}">
			<img src="{% static 'img/Logo.svg' %}" alt="CakeBake">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#step3">Создать торт</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#step2">Каталог</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#step4">Оплата и доставка</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="#Contacts">Контакты</a>
				</li>
				<li class="nav-item d-block d-xl-flex flex-column align-items-end me-5">
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">8 (495) 000-00-00</small>
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">Пн - Вс 10:00—20:00</small>
				</li>
				<li class="nav-item d-flex align-items-center">
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src="{% static 'img/shopping-cart.svg' %}" alt="">
						<!--метка на иконке, убрать класс d-none чтоб появилась-->
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8 d-none">1</span>
					</a>
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#RegModal" data-bs-toggle="modal">
						<img src="{% static 'img/user.svg' %}" alt="">
						<!--метка на иконке, убрать класс d-none чтоб появилась-->
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8 d-none">1</span>
					</a>
					<a class="nav-link fw-lighter cake_grey fs_12 d-none" href="#">
						Ирина
					</a>
				</li>
			</ul>
		</div>
	</nav>
</header>
<main>
{% block content %}
{% endblock %}
</main>
<footer class="mt-5 cake__bg_blue" id="Contacts">
	<div class="container my-5 py-5">
		<div class="row">
			<div class="col-4 col-xl-2 d-flex flex-column">
				<div>
					<img src="{% static 'img/Logo.svg' %}" alt="CakeBake" class="mb-2">
				</div>
				<small class="text-white fs_12">©2022 CakeBake</small>
				<small class="text-white fs_12">Все права защищены.</small>
				<div class="flex-grow-1 d-flex align-items-end">
					<small class="text-white fs_12">г. Москва,  Большой Козловский пер., д. 12</small>
				</div>
			</div>
			<div class="col-4 col-xl-2 d-flex flex-column">
				<a href="#step3" class="text-decoration-none text-white">Создать торт</a>
				<a href="#step2" class="text-decoration-none text-white">Каталог</a>
				<a href="#Contacts" class="text-decoration-none text-white">Контакты</a>
			</div>
			<div class="col-12 col-xl-6 d-flex flex-column align-items-start align-items-xl-end mt-3 mt-xl-0">
				<a href="https://vk.com/devmanorg"><img src="{% static 'img/vk.svg' %}" alt="VK" class="mb-3 mb-xl-5"></a>
				<small class="text-white fs_12">8 (495) 000-00-00</small>
				<small class="text-white fs_12">info@cakebake.ru</small>
				<small class="text-white fs_12">Пн - Вс 10:00—20:00</small>
			</div>
		</div>
	</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/registration.js' %}"></script>
</body>
</html>

bakery/templates/cancel.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <style>
    body {
      text-align: center;
      padding: 120px 0;
      background: #EBF0F5;
    }
    h1 {
      color: #E74C3C;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-weight: 900;
      font-size: 40px;
      margin-bottom: 10px;
    }
    p {
      color: #404F5E;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size: 20px;
      margin: 0;
    }
    i {
      color: #E74C3C;
      font-size: 100px;
      line-height: 200px;
      margin-left: -15px;
    }
    .card {
      background: white;
      padding: 60px;
      border-radius: 4px;
      box-shadow: 0 2px 3px #C8D0D8;
      display: inline-block;
      margin: 0 auto;
    }
  </style>
  <body>
    <div class="card">
      <div style="border-radius: 200px; height: 200px; width: 200px; background: #F8FAF5; margin: 0 auto;">
        <i class="crossmark">✖</i>
      </div>
      <h1>Ошибка!</h1>
      <p>Произошла ошибка при обработке запроса;<br />пожалуйста, попробуйте еще раз позже.</p>
      <a href="{% url 'bakery:main_page' %}" class="btn text-white rounded-pill px-5 mt-3 shadow-none cake__button cake__bg_pink">На главную</a>
    </div>
  </body>
{% endblock %}

bakery/templates/lk-order.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="Style.css">
	<!-- Для разработки: -->
	<script src="https://unpkg.com/vue@3"></script>
	<!-- Для продакшина: -->
	<!-- <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script> -->
	<script src="https://unpkg.com/vee-validate"></script>
	<title>Личный кабинет</title>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-4">
	<div class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="#">
			<img src="img/Logo.svg" alt="CakeBake">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#step3">Создать торт</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#step2">Каталог</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#step4">Оплата и доставка</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#Contacts">Контакты</a>
				</li>
				<li class="nav-item d-block d-xl-flex flex-column align-items-end me-5">
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">8 (495) 000-00-00</small>
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">Пн - Вс 10:00—20:00</small>
				</li>
				<li class="nav-item d-flex align-items-center">
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src="img/shopping-cart.svg" alt="">
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8">1</span>
					</a>
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src="img/user.svg" alt="">
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8">1</span>
					</a>
					<a class="nav-link fw-lighter cake_grey fs_12" href="#">
						Ирина
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div class="container mt-header mb-5">
	<div class="row mt-5">
		<div class="col-12 col-xxl-6 d-flex justify-content-center">
			<div><img src="img/Cake2.png" alt=""></div>
		</div>
		<div class="col-12 col-xxl-6 d-flex flex-column justify-content-center align-items-center align-items-xxl-start" id="LK">
			<form class="d-none">
				<input v-model="Name" name="NAME">
				<input v-model="Phone" name="PHONE">
				<input v-model="Email" name="EMAIL">
				<button type="submit" ref="HiddenFormSubmit">Apply Changes</button>
			</form>
			<v-form :validation-schema="Schema" @submit="ApplyChanges">
				<div class="d-flex w-100 justify-content-center justify-content-xxl-between align-items-center">
					<h1 class="font_Gogh fs_40 cake_blue">Личный кабинет</h1>
					<button v-if="!Edit" @click="Edit = true" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-pencil-fill" viewBox="0 0 16 16">
							<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
						</svg>
					</button>
					<button v-if="Edit" type="submit" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-check-lg" viewBox="0 0 16 16">
							<path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
						</svg>
					</button>
				</div>
				<div class="d-flex">
					<ul class="list-group">
						<li class="list-group-item border-0 ps-0">
							<span class="fs_40 cake_blue">Имя</span>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Телефон</h1>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Почта</h1>
						</li>
					</ul>
					<ul class="list-group">
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Name" type="text" name="name_format" id="name" :readonly="!Edit" class="form-control my-2 i cake__textinput"></v-field>
							<error-message name="name_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Phone" type="text" name="phone_format" id="phone" :readonly="!Edit" class="form-control my-2 cake__textinput"></v-field>
							<error-message name="phone_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Email" type="text" name="email_format" id="email" :readonly="!Edit" class="form-control my-2 cake__textinput"></v-field>
							<error-message name="email_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
					</ul>
				</div>
			</v-form>
			<h2 class="fs_40 cake_pink mt-5">Мои заказы</h2>
			<section class="my-2">
				<span class="cake_blue lk__order d-flex" data-bs-toggle="modal" data-bs-target="#OrderModal2">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
					</svg>
					<span class="ms-1">#2239400223 Свадебный торт “VIP”</span>
				</span>
				<aside class="modal fade" id="OrderModal2" tabindex="-1" aria-labelledby="ModalLabel2" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title cake_pink" id="ModalLabel2">#2239400223 Свадебный торт “VIP””</h5>
								<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							</div>
							<div class="modal-body">
								<span class="cake_blue">Уровней: 1</span><br>
								<span class="cake_blue">Форма: круг</span><br>
								<span class="cake_blue">Топпинг: без</span><br>
								<span class="cake_blue">Ягоды: нет</span><br>
								<span class="cake_blue">Декор: нет</span><br>
								<span class="cake_blue">Без надписи</span><br>
								<span class="cake_pink">Цена: 1000₽</span>
							</div>
							<div class="modal-footer d-flex justify-content-between">
								<span class="cake_blue d-flex">Статус: В доставке</span>
								<span class="cake_blue d-flex align-items-center">Время доставки: ?</span>
							</div>
						</div>
					</div>
				</aside>
			</section>
			<section class="my-2">
				<span class="cake_blue lk__order d-flex" data-bs-toggle="modal" data-bs-target="#OrderModal1">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
					</svg>
					<span class="ms-1">#45575879537 Торт “Черепаха”</span>
				</span>
				<aside class="modal fade" id="OrderModal1" tabindex="-1" aria-labelledby="ModalLabel1" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title cake_pink" id="ModalLabel1">#45575879537 Торт “Черепаха”</h5>
								<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							</div>
							<div class="modal-body">
								<span class="cake_blue">Уровней: 2</span><br>
								<span class="cake_blue">Форма: квадрат</span><br>
								<span class="cake_blue">Топпинг: белый соус</span><br>
								<span class="cake_blue">Ягоды: безе</span><br>
								<span class="cake_blue">Декор: нет</span><br>
								<span class="cake_blue">С днём рождения</span><br>
								<span class="cake_pink">Цена: 2550₽</span>
							</div>
							<div class="modal-footer d-flex justify-content-between">
								<span class="cake_blue">Статус: Выполнен</span>
								<span class="cake_blue">Время доставки: ?</span>
							</div>
						</div>
					</div>
				</aside>
			</section>

			<button class="btn text-white rounded-pill align-self-end px-5 mt-3 shadow-none cake__button cake__bg_pink">Выйти</button>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="lk.js"></script>
</body>
</html>

bakery/templates/success.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
      body {
        text-align: center;
        padding: 120px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
<body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Выполнено!</h1>
        <p>Оплата прошла успешно;<br/> мы скоро свяжемся с вами!</p>
        <a href="{% url 'bakery:main_page' %}" class="btn text-white rounded-pill px-5 mt-3 shadow-none cake__button cake__bg_pink">На главную</a>
      </div>
    </body>
{% endblock %}